### ISSUE TITLE
LocalPravegaEmulator does not work with ZooKeeper 3.6.x on the classpath

### ISSUE THREAD

**Issue by eolivelli** [pravega/pravega#4966]
**Problem description**
While updating ZooKeeper dependency from 3.5.6 to 3.6.1 in EmailSuccess we got into this problem.

```
java.lang.NoSuchMethodError: 'void org.apache.zookeeper.server.ServerCnxnFactory.configure(java.net.InetSocketAddress, int, boolean)'
	at io.pravega.segmentstore.storage.impl.bookkeeper.ZooKeeperServiceRunner.start(ZooKeeperServiceRunner.java:106)
	at io.pravega.local.InProcPravegaCluster.startLocalZK(InProcPravegaCluster.java:214)
	at io.pravega.local.InProcPravegaCluster.start(InProcPravegaCluster.java:186)
	at io.pravega.local.LocalPravegaEmulator.start(LocalPravegaEmulator.java:147)**Problem location**
```

**Suggestions for an improvement**
- Implement a flag to not start ZooKeeper Server in LocalPravegaEmulator/InProcPravegaCluster or use Curator TestingServer (that handles compatibility with all versions of ZK)
- Upgrade to ZooKeeper 3.6.1

**Comment by eolivelli** [comment]
It also does not work with Latest Curator 5.x

```
java.lang.NoSuchMethodError: 'org.apache.curator.framework.listen.ListenerContainer org.apache.curator.framework.recipes.cache.NodeCache.getListenable()'
	at io.pravega.segmentstore.server.host.ZKSegmentContainerMonitor.initialize(ZKSegmentContainerMonitor.java:124)
	at io.pravega.segmentstore.server.host.ZKSegmentContainerMonitor.initialize(ZKSegmentContainerMonitor.java:107)
	at io.pravega.segmentstore.server.host.ZKSegmentContainerManager.initialize(ZKSegmentContainerManager.java:61)
	at io.pravega.segmentstore.server.store.ServiceBuilder.initialize(ServiceBuilder.java:236)
	at io.pravega.segmentstore.server.host.ServiceStarter.start(ServiceStarter.java:95)
	at io.pravega.local.InProcPravegaCluster.startLocalSegmentStore(InProcPravegaCluster.java:307)
	at io.pravega.local.InProcPravegaCluster.startLocalSegmentStores(InProcPravegaCluster.java:252)
```

**Comment by eolivelli** [comment]
@RaulGracia @ravisharda is it possible to upgrade ZK and Curator dependencies for 0.8.0 ?

Current workaround is to isolate unit tests of Pravega integration in a separate module that forces the version of Curator and ZooKeeper, but it is not ideal.

**Comment by RaulGracia** [comment]
Thanks @eolivelli! We are close to testing/releasing 0.8, so I don't know if upgrading such dependencies is going to be the safest thing to do at this point. As it is not a trivial upgrade and it may involve other changes, would it be ok if we address this issue for 0.9 version?

**Comment by eolivelli** [comment]
I see the point about fix dangerous upgrade.
We found a workaround and we can live with it.

**Comment by RaulGracia** [comment]
Fixed via #4999.
